# -*- coding: utf-8 -*-
"""segmentadorFrames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u72fj2eX7m9D7VSa8mo-OnsJmFWLWojn
"""

import cv2
count = 0;
for i in range(154):
  vidcap = cv2.VideoCapture('/content/drive/My Drive/keras/videos/bebe/bebe'+str(i)+'.MOV')
  while(vidcap.isOpened()):
    ret,frame = vidcap.read()
    if ret == False:
      break
    cv2.imwrite("/content/drive/My Drive/keras/data0_01/bebe/%06d.jpg" % count, frame)     # save frame as JPEG file
    count += 1
vidcap.release()
cv2.destroyAllWindows()

from google.colab import drive
drive.mount('/content/drive')