# -*- coding: utf-8 -*-
"""segmentador.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Cw8ddUljYSOkjucKjNOVd0vv6ZTyleT
"""

import cv2
print(cv2.__version__)
count = 0
for i in range(100):
  vidcap = cv2.VideoCapture('/content/drive/My Drive/keras/videos/bebe/Bebe'+str(i+65)+'.MOV')
  success,image = vidcap.read()
  success = True
  count_frame = 0
  while success:
    vidcap.set(cv2.CAP_PROP_POS_MSEC,(count_frame*10))    # 10 para 0,01 s y 40 para 0,04s 
    success,image = vidcap.read()
    if success == True:
      image = cv2.resize(image, (224, 224))
      image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
      cv2.imwrite("/content/drive/My Drive/keras/data0_01e/bebe/%08d.jpg" % count, image)     # save frame as JPEG file
      count = count + 1
      count_frame = count_frame + 1